### ISSUE TITLE
Display song title and artist name not name of file in screen for adding soundtrack

### ISSUE THREAD

**Issue by khar0** [khar0/blahblah-ios-app#1]

**Comment by khar0** [comment]
We need to store for each song the artist name and song name e.g. for the four songs in library it should be:

Artist | Song
------------------
Wale | Sabotage
Frank Ocean | Swim Good
The Weeknd | The Party & The After Party
Miguel | How Many Drinks?

**Comment by khar0** [comment]
We need to store for each song the artist name and song name e.g. for the four songs in library it should be:

Artist | Song
Wale | Sabotage
Frank Ocean | Swim Good
The Weeknd | The Party & The After Party
Miguel | How Many Drinks?

**Comment by hanjinghe** [comment]
![Screenshot at Jul 13 08-39-56](https://user-images.githubusercontent.com/3221018/61164655-fac63480-a549-11e9-8f55-f9fea1ed2f02.png)
please check screenshot. We are saving  all sound informations to firebase. You can edit/add songs anytime.

**Comment by hanjinghe** [comment]
updated firebase db
