### ISSUE TITLE
[High Priority] Create new format for Yo! MTV Raps posts

### ISSUE THREAD

**Issue by khar0** [khar0/blahblah-ios-app#12]
1. We will either Use Swift animations to replicate format for the border frame and Yo! MTV Raps logo animation. See contents of attached zip file or overlay a gif with a transparent background that I edited.
[yo_mtv_raps_format_example.zip](https://github.com/khar0/blahblah-ios-app/files/3402506/yo_mtv_raps_format_example.zip)

2. This format is only activated when user selects this 'Yo! MTV Wraps' in the modal that appears when user clicks 'post.

3. For this format - user cannot add any additional effects apart from picking a sound track and flipping camera - @khar0  will create separate ticket to show what the sound selection screen should look like.

4. When video is uploaded - there is a clip that needs to be automatically added before the start of the user's video - @khar0  will provide example screen shot of this.

5. In preview mode and when uploaded, we will display the user's username and name in a glow font - @khar0 will provide example screen shot of this.

**Comment by khar0** [comment]
![yo! mtv raps border](https://user-images.githubusercontent.com/37517980/61537921-9834d300-aa38-11e9-8ff8-f068314f5aa3.gif)

**Comment by khar0** [comment]
Specification for Glow Font:

<img width="638" alt="Screenshot 2019-07-21 at 15 14 06" src="https://user-images.githubusercontent.com/37517980/61591799-16c17a00-abcb-11e9-82ed-ac852489eb35.png">

This is the closest match I found:
<img width="1228" alt="Screenshot 2019-07-21 at 15 20 54" src="https://user-images.githubusercontent.com/37517980/61591804-2ccf3a80-abcb-11e9-8843-3e5046029d9b.png">
https://www.myfonts.com/fonts/urw/gothic-outline/gothic-outline-title-d/

OTF file:
http://fontsgeek.com/fonts/Gothic-Outline-Title-D-OT-Regular
[Gothic Outline Title D OT Regular.zip](https://github.com/khar0/blahblah-ios-app/files/3414636/Gothic.Outline.Title.D.OT.Regular.zip)

**Comment by khar0** [comment]
Follow-ups:

Positioning of upload and cancel button
![IMG_1435](https://user-images.githubusercontent.com/37517980/61593402-57c38980-abdf-11e9-98c7-1d343fa0e4b4.PNG)

Let's address design for header in play-back screen
![IMG_1437](https://user-images.githubusercontent.com/37517980/61593420-93f6ea00-abdf-11e9-83f7-caa545a59c8d.PNG)

I can see the border for format is stretched - i think this is expected. I'll discuss with client how we can get a better version. Or if we need to do a manual work around.

**Comment by hanjinghe** [comment]
1. fixed position issue
2. for streched issue, we do not need to discuss with client
Can you provide me full gif file (means include "Yo!" string in whole image with red colored background
)

**Comment by khar0** [comment]
> 1. fixed position issue
> 2. for streched issue, we do not need to discuss with client
>    Can you provide me full gif file (means include "Yo!" string in whole image with red colored background
>    )

![ezgif com-gif-maker (3)](https://user-images.githubusercontent.com/37517980/61638915-af72fb00-ac9a-11e9-8a85-a7dc37fb2d55.gif)
![ezgif com-gif-maker (5)](https://user-images.githubusercontent.com/37517980/61638917-af72fb00-ac9a-11e9-9427-353f4860361d.gif)

**Comment by khar0** [comment]
![YO! Pattern - Blue](https://user-images.githubusercontent.com/37517980/61646226-17304280-aca9-11e9-93b8-cada948b8f6c.jpg)
https://user-images.githubusercontent.com/37517980/61646226-17304280-aca9-11e9-93b8-cada948b8f6c.jpg

![YO! Pattern - Pink](https://user-images.githubusercontent.com/37517980/61646227-17304280-aca9-11e9-8da2-765e435348ca.jpg)
https://user-images.githubusercontent.com/37517980/61646227-17304280-aca9-11e9-8da2-765e435348ca.jpg

![YO! Pattern - Red](https://user-images.githubusercontent.com/37517980/61646228-17c8d900-aca9-11e9-934c-81eff3542f7c.jpg)
https://user-images.githubusercontent.com/37517980/61646228-17c8d900-aca9-11e9-934c-81eff3542f7c.jpg

![YO! Pattern - Teal](https://user-images.githubusercontent.com/37517980/61646229-17c8d900-aca9-11e9-91c5-0394c7d3a854.jpg)
https://user-images.githubusercontent.com/37517980/61646229-17c8d900-aca9-11e9-91c5-0394c7d3a854.jpg

**Comment by khar0** [comment]
Hi Han - let's discuss changes for this format. Key things:

1. We need to fix issue with border
2. Test video post of this format from start to finish.

**Comment by hanjinghe** [comment]
done

**Comment by hanjinghe** [comment]
fixed
