### ISSUE TITLE
Update screen for 'Add a Sound' to allow user to select songs available on BlahBlah, from Spotify or from own music on phone library

### ISSUE THREAD

**Issue by khar0** [khar0/blahblah-ios-app#13]
![20190718_150435](https://user-images.githubusercontent.com/37517980/61459696-9c47ee80-a96d-11e9-965a-beb4433fe223.jpg)
![15634552218375687639259395514320](https://user-images.githubusercontent.com/37517980/61459746-b8e42680-a96d-11e9-84f3-506ccb9c86d2.jpg)

1. Change title of screen to 'Add Soundtrack'

2a. User can search by artist or song title. 
2b. Add a 3 button tab menu for user to select songs from 3 different options. Default is 'BlahBlah Music' option. Make button background in black with white text to show this button is active. For non-active buttons, background is white with black text.
2c. The 'BlahBlah Music' is the current screen layout 
2d. For Spotify option we want to use Spotify api to allow user to use music from Spotify. I will check if this option is possible. Just have button as placeholder for now. 
2e. For 'My Music' user csn select songs from Music folder in phone. I will provide separate screenshot for this layout. 

3a. We will show the top 5 songs users have selected in the app for videos. So we need to keep a count of how many times users picks song in database 
3b. We will provide a add/(+) button to make it more obvious to user how to select a song

4. I will provide songs for instrumentals - so we will need an attribute for each song in database to know if song is an instrumental 

5. These are normal songs like we currently have in the app. Sort in alphabetical order by song name

**Comment by khar0** [comment]
Spotify logo: https://newsroom.spotify.com/media-kit/logo-and-brand-assets/

**Comment by khar0** [comment]
As discussed - ignore 'No instrumental' song option in screenshot as this screen will only be activated if user wants to add a soundtrack

**Comment by khar0** [comment]
This is the design when user clicks on 'My Music' to select music from the music library on their phone 
![20190718_160713](https://user-images.githubusercontent.com/37517980/61466404-26964f80-a97a-11e9-9971-a610d205d4ea.jpg)

**Comment by hanjinghe** [comment]
done
