### ISSUE TITLE
Re-style format selection modal - ensure constraints look fine for big and small screen

### ISSUE THREAD

**Issue by khar0** [khar0/blahblah-ios-app#14]
[Formats Selection Design.pptx](https://github.com/khar0/blahblah-ios-app/files/3411777/Formats.Selection.Design.pptx)

![yo! mtv raps format](https://user-images.githubusercontent.com/37517980/61548253-932e4e80-aa4d-11e9-87f1-4b2bad892234.gif)
https://user-images.githubusercontent.com/37517980/61548253-932e4e80-aa4d-11e9-87f1-4b2bad892234.gif

**Comment by khar0** [comment]
Note - I have added the format video for YO! MTV Raps

[yo_mtv_raps_format_video.zip](https://github.com/khar0/blahblah-ios-app/files/3411817/yo_mtv_raps_format_video.zip)

**Comment by hanjinghe** [comment]
Done
