### ISSUE TITLE
Re-style landing screen to go back to original

### ISSUE THREAD

**Issue by khar0** [khar0/blahblah-ios-app#20]
<img width="667" alt="Screenshot 2019-07-22 at 11 55 07" src="https://user-images.githubusercontent.com/37517980/61623790-a91f5780-ac77-11e9-8e3d-d70ab7cb4ba1.png">

1. Change text "NEVER MIND THE RESUME, THIS IS"  to "CREATE YOUR FAVOURITE"
2. Change text "POP-RECRUITMENT" to "TV SHOWS"
3. Use this logo for Discovery instead
![discovery_channel_official](https://user-images.githubusercontent.com/37517980/61631741-6bc4c500-ac8b-11e9-972b-718d5edb8c1c.png)
https://user-images.githubusercontent.com/37517980/61631741-6bc4c500-ac8b-11e9-972b-718d5edb8c1c.png

**Comment by hanjinghe** [comment]
done
