### ISSUE TITLE
Add 3 more channels to TV remote menu and re-style

### ISSUE THREAD

**Issue by khar0** [khar0/blahblah-ios-app#21]
<img width="297" alt="Screenshot 2019-07-22 at 12 08 10" src="https://user-images.githubusercontent.com/37517980/61624712-70807d80-ac79-11e9-9c18-d6e588f82d07.png">

**Changes Needed:**

1.Add space between heart icon and “=”
2.Use icon for padlock and tv remote symbol in attached ticket
3.Add padlock symbol to all channel icons apart from ‘MTV Base’
4.Let user also be able to swipe left to right open menu (so two options to open menu)
5.Add in third column additional icons for Food Network, Travel Channel, Spike,  (still keep menu width to 50% of screen).
6. Synchronize the salary rate number in menu with the salary rate in home feed. Note: Still keep salary rate in feed as whole number. When number increases - arrow is green-arrow-up-icon, when number decreases, arrow is red-arrow-down-icon.

**Assets:**
_Spike Icon_
![Image from iOS (1)](https://user-images.githubusercontent.com/37517980/61624804-a0c81c00-ac79-11e9-8c3f-258da3904f3a.png)
https://user-images.githubusercontent.com/37517980/61624804-a0c81c00-ac79-11e9-8c3f-258da3904f3a.png

_Travel Channel Icon_
![Image from iOS (2)](https://user-images.githubusercontent.com/37517980/61624805-a0c81c00-ac79-11e9-81b7-a9367deeb1ac.png)
https://user-images.githubusercontent.com/37517980/61624805-a0c81c00-ac79-11e9-81b7-a9367deeb1ac.png

_Food Network Icon_
![Image from iOS](https://user-images.githubusercontent.com/37517980/61624806-a160b280-ac79-11e9-9b60-f480fd9fcbfd.png)
https://user-images.githubusercontent.com/37517980/61624806-a160b280-ac79-11e9-9b60-f480fd9fcbfd.png

_Padlock Icon_
![lock](https://user-images.githubusercontent.com/37517980/61634830-8189b880-ac92-11e9-8465-a4af67910a98.png)
https://user-images.githubusercontent.com/37517980/61634830-8189b880-ac92-11e9-8465-a4af67910a98.png

**Comment by hanjinghe** [comment]
done
