### ISSUE TITLE
[Build 79 Follow-ups] Salary Rate changes in Drawer Menu not reflecting

### ISSUE THREAD

**Issue by khar0** [khar0/blahblah-ios-app#26]
Changes to rename rate to 'Intern Salary Rate' and re-distribute pricing for R-Like not taking effect.

1) I have fixed the pricing distribution issue in the menu - we also didn't initialise the timer to scheduler randomising the salary rate.

2) I had made a change to change 'Salary Rate' to 'Intern Salary Rate' - but seems it wasn't merged properly. Let's also make sure we always releasing from master branch.

**Comment by hanjinghe** [comment]
Fixed
