### ISSUE TITLE
 [Build 79 Follow-ups] Need button to enable user to select TV Show Formats menu

### ISSUE THREAD

**Issue by khar0** [khar0/blahblah-ios-app#27]
This is the flow:

User select button to create post
Formats menu appears
User clicks cancel button to cancel format selection
Normal camera view appears
User is not able to select TV show format menu again

Fix:
When user clicks on current formats button - this should open the TV show formats menu. 

We will figure out later what to do with the standard formats 1-4.

**Comment by hanjinghe** [comment]
Fixed
