### ISSUE TITLE
[Build 79 Follow-ups] Cancel button in camera screen not very visible

### ISSUE THREAD

**Issue by khar0** [khar0/blahblah-ios-app#28]
![1563824238534](https://user-images.githubusercontent.com/37517980/61659896-f5df4e80-acc8-11e9-902a-4bf60475077e.JPEG)

1) Use the 'X' icon for cancel button
https://user-images.githubusercontent.com/37517980/61659797-b1ec4980-acc8-11e9-9db9-ab475422d414.png

2) Also for normal camera view - make the camera flip icon same size as filters icon. Currently too small relative to other icons.

![1563824390827](https://user-images.githubusercontent.com/37517980/61660062-553d5e80-acc9-11e9-9256-9b0415879759.JPEG)

**Comment by hanjinghe** [comment]
Fixed
