### ISSUE TITLE
Display TV channels that users can create content for

### ISSUE THREAD

**Issue by khar0** [khar0/blahblah-ios-app#3]
On the landing page: Beneath "Never mind the resume ..." add a view component where we use animation to fade in each of the text one at a time for 2 seconds and fade out for 0 seconds: MTV, MTV Base, Comedy Central, Spike, Discovery Channel, BET

**Comment by khar0** [comment]
replace the text "Never mind the resume" with "Create My ..." (b) Delete the text "Pop Recruitment"

**Comment by hanjinghe** [comment]
completed
