### ISSUE TITLE
Re-style Gif for Yo! MTV raps format in home feed

### ISSUE THREAD

**Issue by khar0** [khar0/blahblah-ios-app#34]
1. Currently we are using the default graphics for showing MTV Raps format. Don't display the pink and blue title. Please change like this:
<img width="950" alt="Screenshot 2019-07-23 at 08 58 58" src="https://user-images.githubusercontent.com/37517980/61689795-2bffeb00-ad28-11e9-8461-855b4a89f8a1.png">

2. #yomtvraps should be populated by default as on of the hashtags. I.e. the name of the show should be populated by default for each format. Can we make specify this is in the postformatinfo object so it is easy to add for other formats.

3. Hashtags should not have spaces in them. This is for all posts on BlahBlah not just this format. I had cleaned this up in the list I provided a while back. Has something chan

**Comment by hanjinghe** [comment]
done
