### ISSUE TITLE
We have entries for empty soundtrack

### ISSUE THREAD

**Issue by khar0** [khar0/blahblah-ios-app#38]
We have entry for empty soundtrack in 'add soundtrack' screen displaying in trending and tracks section

![1563877538574](https://user-images.githubusercontent.com/37517980/61705163-9410fa00-ad45-11e9-94c2-ede2e48f4282.JPEG)
![1563877538709](https://user-images.githubusercontent.com/37517980/61705165-94a99080-ad45-11e9-93bc-b62d05900360.JPEG)

**Comment by hanjinghe** [comment]
Fixed
