### ISSUE TITLE
Add menu for user to change TV channel

### ISSUE THREAD

**Issue by khar0** [khar0/blahblah-ios-app#4]
On swiping screen, let menu appear on left (see screenshot)
![IMG-20190712-WA0005](https://user-images.githubusercontent.com/37517980/61201569-d51d6480-a6dc-11e9-94d1-833c07983656.jpg).

This menu will basically allow user to change the channel ... 

(a) at the moment we only have one channel "MTV Base" ... so grey out the other icons. 

(b) where you see the text "Ygor Omar Francisco" replace it with "Channels Available" 

(c) arrange the icons 3 in a row and add the icon text (e.g. MTV Base) below each icon in a smaller font

**Comment by hanjinghe** [comment]
Can you provide MTV and Discovery channel icons?

**Comment by hanjinghe** [comment]
other things are done

**Comment by khar0** [comment]
![discovery_channel_logo_colour](https://user-images.githubusercontent.com/37517980/61364129-83640e00-a885-11e9-9d0d-2b55628ed421.png)

**Comment by khar0** [comment]
![mtv_logo_yellow](https://user-images.githubusercontent.com/37517980/61364558-65e37400-a886-11e9-9fde-e16b3dc3db32.png)

**Comment by hanjinghe** [comment]
done
