### ISSUE TITLE
Add tv show formats menu for new post creation

### ISSUE THREAD

**Issue by khar0** [khar0/blahblah-ios-app#6]
Now, when user clicks to create a new post .. a new modal should appear (see image). 

![Screenshot_20190715-080457_WhatsApp](https://user-images.githubusercontent.com/37517980/61201818-8cb27680-a6dd-11e9-9dc9-ebda54b3312a.jpg)

The modal has 2 parts: a horizontal scroll view for icons MTV Base, BET, Comedy Central, Discovery Channel, Spike, BET etc ... and then then below it a  vertical scroll view of the tv shows associated with each icon (these will be images for formats).

For the time being display the image for the basic formats we have. I will give you the image files for what you see in the screen shot above.

**Comment by hanjinghe** [comment]
an you provide all images ?

**Comment by hanjinghe** [comment]
done. But i need correct images

**Comment by khar0** [comment]
Thanks Han, got feedback. Let's change the icons to text instead e.g. MTV Base, MTV, Discovery Channel, TLC, BET. Use white text in bold (size 14pt). 

And when the tab is active we

**Comment by khar0** [comment]
I will provide images from client.

**Comment by khar0** [comment]
For the channels  - let's show only MTV Base for now and place it in center. Formats for the other shows are not yet available.

**Comment by khar0** [comment]
![20190717_144805](https://user-images.githubusercontent.com/37517980/61376727-fed3b880-a8a1-11e9-8565-cdcd53bf68f1.jpg)

**Comment by khar0** [comment]
1. So when user click post button - the camera view with the tv channel logo is active in background but slightly blurred out. For now we only have one channel, so display MTV Base channel logo
2. On top of this we display modal for user to select a tv show format to use for post creation
3. This modal has 3 parts: 
     (a) "Choose a tv show to create"
     (b) The menu to select the channel - again, only MTV Base for now
     (c) Associated with the selected channel is a scroll view of tv show formats

For 3(c) We only have 2 tv show formats for now:
(i) default format with just the logo
(ii) Yo! MTV Raps format

The default format is the current behaviour of the app where the user can record any kind of content they wish.

The Yo! MTV Raps format is a specific kind of format for <60s videos. I will create a separate ticket for what the camera preview and editing options should look like when user selects this format.

**Comment by khar0** [comment]
Hi Han - please use this gif as placeholder for now. See .mp4 file 

[wetransfer-e6275f.zip](https://github.com/khar0/blahblah-ios-app/files/3404220/wetransfer-e6275f.zip)

**Comment by hanjinghe** [comment]
done
