### ISSUE TITLE
Move currency per like feature to side menu

### ISSUE THREAD

**Issue by khar0** [khar0/blahblah-ios-app#7]
In the feed, when user scrolls all the way down the page - currency for like appears. 

(a) Delete this page. Feed should only have videos.

(b) Instead on the swipe left menu ... add a section below the tv channel icons where we display "1 🖤 = 1 Rand" ... I will build a service where you will be able to fetch the price of a heart in real time.

**Comment by hanjinghe** [comment]
done. I need api for getting price of a heart

**Comment by khar0** [comment]
Thanks - will provide api for you to integrate tomorrow.

**Comment by khar0** [comment]
Will open new ticket to fetch rate from API.
