### ISSUE TITLE
Only play gif in feed for video that is active as user scrolls

### ISSUE THREAD

**Issue by khar0** [khar0/blahblah-ios-app#9]
In feed ... only 1 gif should play at a time, and it should be the one in view on user's screen. We can still continue to fetch posts in batches.

This will keep feed simple for user because right now there is a lot happening on screen. And we need to performance tune feed loading.

**Comment by khar0** [comment]
Hi Han - think this was misunderstood ... the videos in feed shouldn't take the full screen ... they should still be the same size as before but only one gif should play I.e. the video in centre of screen.

**Comment by hanjinghe** [comment]
fixed
